server:
  port: 8080

spring:
  application:
    name: se182983-sba301
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=sba301_orchid;encrypt=true;trustServerCertificate=true
    username: sa
    password: Tgk@170504
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  ttl: 3600000
